/**
 * LexisAI Groq Llama-4 Client & JSON Array Hunter
 * Path: /js/api/groqClient.js
 */
import { withRetry } from './geminiRetry.js';

class GroqClient {
    async generateJSON(messages) {
        const apiCall = async () => {
            const response = await fetch('/api/groq', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ messages: messages, stream: false })
            });

            if (!response.ok) throw new Error(`Groq Gateway Error: ${response.status}`);
            return await response.json();
        };

        const data = await withRetry(apiCall);
        const rawText = data.choices[0]?.message?.content || "";
        
        // JSON Array Hunter: Strips out 
http://googleusercontent.com/immersive_entry_chip/0

---

### `js/api/tavilySearch.js`
**Explanation:** Maps multiple queries generated by Groq into parallel searches.

```javascript
/**
 * LexisAI Search Batch Orchestrator
 * Path: /js/api/tavilySearch.js
 */
import { TavilyClient } from './tavilyClient.js';
import { TavilyCompressor } from './tavilyCompressor.js';
import { eventBus } from '../core/eventBus.js';

export class TavilySearch {
    static async executeBatch(queriesArray) {
        if (!Array.isArray(queriesArray) || queriesArray.length === 0) return [];
        
        try {
            // Execute all queries in parallel
            const searchPromises = queriesArray.map(q => TavilyClient.executeQuery(q));
            const rawResults = await Promise.all(searchPromises);
            
            let compressedMasterList = [];
            
            // Compress and merge results
            rawResults.forEach(raw => {
                const compressed = TavilyCompressor.process(raw);
                compressedMasterList.push(...compressed);
            });

            // Deduplicate by URL to save tokens
            const uniqueSources = Array.from(new Map(compressedMasterList.map(item => [item.url, item])).values());
            
            return uniqueSources;
            
        } catch (error) {
            eventBus.emit('FATAL_ERROR', { message: `[SEARCH_EXHAUSTION] Batch failed: ${error.message}` });
            return []; // Failsafe recovery, return empty array to prevent complete DAG collapse
        }
    }
}
